version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: |
      sh -c 'npm run migrations && npm run seed && npm run start'
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=note_app
      - JWT_SECRET=1d96412b22826a4e270bb71948310186bc74ca447203375e4dc2ae5673091db4
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=note_app
